#ifndef YADOWNLOADER_GLOBAL_H
#define YADOWNLOADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(YADOWNLOADER_LIBRARY)
#  define YADOWNLOADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define YADOWNLOADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // YADOWNLOADER_GLOBAL_H
